Add support for Intel NUC + GRUB
With this patch OTA integration now supports
boards with GRUB2 boot loaders.

The same patch moves from *.tar.gz to dd based OTA
images:

 - assembling and deploying dd image takes significantly
   less time.
 - its more convenient to do this in qt-ostree, as we
   have all the relevant information available there.

Change-Id: I2d0fb2426360b8afc4e62f2c98c3d7c75a10db07
Reviewed-by: Gatis Paeglis <gatis.paeglis@theqtcompany.com>

diff --git a/dracut/generate-initramfs b/dracut/generate-initramfs
--- a/dracut/generate-initramfs
+++ b/dracut/generate-initramfs
@@ -20,7 +20,6 @@
 ## $QT_END_LICENSE$
 ##
 #############################################################################
-#set -x
 set -e
 
 if [ ! -x "$(which adb)" ] ; then
@@ -29,61 +28,99 @@ if [ ! -x "$(which adb)" ] ; then
 fi
 
 ROOT=$(dirname $(readlink -f $0))
+BOOTLOADER="u-boot"
 
-output=$(adb shell ls /usr/sbin/ostree-prepare-root)
-substring="No such file or directory"
-if [[ $output == *${substring}* ]] ; then
-    echo "error: Failed to find the required binary /usr/sbin/ostree-prepare-root on a device."
-    exit 1
-fi
+detect_target_device()
+{
+    adb pull /etc/hostname
+    DEVICE=$(cat hostname)
+    rm -f hostname
+    if [ -z "${DEVICE}" ] ; then
+        echo "error: no hostname specified in /etc/hostname on a device."
+        exit 1
+    fi
 
-output=$(adb shell ls /lib/systemd/systemd)
-systemd=false
-if [[ $output != *${substring}* ]] ; then
-    systemd=true
-fi
+    case "${DEVICE}" in
+        *nuc*) # Intel NUC
+            BOOTLOADER="grub2"
+            ;;
+    esac
 
-options='/boot/initramfs.img
-        --host-only
-        --add ostree
-        --omit i18n
-        --stdlog 3
-        --force'
+    echo "Detected ${DEVICE} device with ${BOOTLOADER} boot loader."
+}
 
-if [ ${systemd} = true ] ; then
-    # OSTree ships with a dracut module for systemd based images.
-    echo "Generating initramfs for systemd based image ..."
-    adb push ${ROOT}/systemd/01-qt.conf /etc/dracut.conf.d/
-    custom_options='--add systemd'
-else
-    # Deploy our custom dracut module for systemd-less images.
-    echo "Generating initramfs for system v init based image ..."
-    MODULE_PATH=/usr/lib/dracut/modules.d/98ostree/
-    adb shell mkdir -p $MODULE_PATH
-    adb push ${ROOT}/systemv/module-setup.sh $MODULE_PATH
-    adb push ${ROOT}/systemv/prepare-root.sh $MODULE_PATH
-    custom_options='--omit systemd'
-fi
+generate_initramfs()
+{
+    output=$(adb shell ls /usr/sbin/ostree-prepare-root)
+    substring="No such file or directory"
+    if [[ $output == *${substring}* ]] ; then
+        echo "error: Failed to find the required binary /usr/sbin/ostree-prepare-root on a device."
+        exit 1
+    fi
 
-# Terminate when the explicitly required modules could not be found or installed.
-adb shell dracut ${options} ${custom_options} | tee dracut.log
-errors=$(cat dracut.log | grep -i "cannot be found or installed" | wc -l)
-if [ ${errors} -gt 0 ] ; then
-    echo "error: Failed to include the required modules into the initramfs image."
-    exit 1
-fi
+    output=$(adb shell ls /lib/systemd/systemd)
+    systemd=false
+    if [[ $output != *${substring}* ]] ; then
+        systemd=true
+    fi
 
-rm -f initramfs.img
-adb pull /boot/initramfs.img
-device=$(adb shell uname -n | tr -d '\r')
-release=$(adb shell uname -r | tr -d '\r' | cut -d'-' -f1)
-initramfs=initramfs-${device}-${release}
-rm -rf ${initramfs}
-mkimage -A arm -O linux -T ramdisk -a 0 -e 0 -d initramfs.img ${initramfs}
-rm -f initramfs.img
+    options='/boot/initramfs.img
+            --host-only
+            --add ostree
+            --omit i18n
+            --stdlog 3
+            --force'
 
-echo
-echo "Done, generated OSTree boot compatible initramfs:"
-echo
-echo ${initramfs}
-echo
+    if [ ${systemd} = true ] ; then
+        # OSTree ships with a dracut module for systemd based images.
+        echo "Generating initramfs for systemd based image ..."
+        adb push ${ROOT}/systemd/01-qt.conf /etc/dracut.conf.d/
+        custom_options='--add systemd'
+    else
+        # Deploy our custom dracut module for systemd-less images.
+        echo "Generating initramfs for system v init based image ..."
+        MODULE_PATH=/usr/lib/dracut/modules.d/98ostree/
+        adb shell mkdir -p $MODULE_PATH
+        adb push ${ROOT}/systemv/module-setup.sh $MODULE_PATH
+        adb push ${ROOT}/systemv/prepare-root.sh $MODULE_PATH
+        custom_options='--omit systemd'
+    fi
+
+    # Terminate when the explicitly required modules could not be found or installed.
+    adb shell dracut ${options} ${custom_options} | tee dracut.log
+    errors=$(cat dracut.log | grep -i "cannot be found or installed" | wc -l)
+    if [ ${errors} -gt 0 ] ; then
+        echo "error: Failed to include the required modules into the initramfs image."
+        exit 1
+    fi
+
+    rm -f initramfs.img
+    adb pull /boot/initramfs.img
+    device=$(adb shell uname -n | tr -d '\r')
+    release=$(adb shell uname -r | tr -d '\r' | cut -d'-' -f1)
+    INITRAMFS=initramfs-${device}-${release}
+    rm -rf ${INITRAMFS}
+
+    detect_target_device
+
+    if [ "${BOOTLOADER}" = "u-boot" ] ; then
+        # Add u-boot header.
+        mkimage -A arm -O linux -T ramdisk -a 0 -e 0 -d initramfs.img ${INITRAMFS}
+        rm -f initramfs.img
+    else
+        mv initramfs.img ${INITRAMFS}
+    fi
+}
+
+main()
+{
+    generate_initramfs
+
+    echo
+    echo "Done, generated OSTree boot compatible initramfs:"
+    echo
+    echo ${INITRAMFS}
+    echo
+}
+
+main
