Try to use adb from SDK
If adb is not found in PATH then the one from Qt SDK will be used as well.

Change-Id: I35726a94d3c2b00118be29f7285cc8ed6f377d38
Reviewed-by: Gatis Paeglis <gatis.paeglis@theqtcompany.com>

diff --git a/dracut/generate-initramfs b/dracut/generate-initramfs
--- a/dracut/generate-initramfs
+++ b/dracut/generate-initramfs
@@ -22,17 +22,25 @@
 #############################################################################
 set -e
 
-if [ ! -x "$(which adb)" ] ; then
-    echo "Needed command 'adb' not found in PATH."
-    exit 1
-fi
-
 ROOT=$(dirname $(readlink -f $0))
+ADB=$(which adb) || true
+
+if [ ! -x "${ADB}" ] ; then
+    # No system adb found. Try the one from Qt SDK.
+    ADB="${ROOT}"/../../../b2qt/adb
+    if [ ! -x "${ADB}" ] ; then
+        echo "Needed command 'adb' not found in PATH."
+        exit 1
+    fi
+fi
+ADB=$(readlink -e "${ADB}")
+echo "Using adb from ${ADB}"
+
 BOOTLOADER="u-boot"
 
 detect_target_device()
 {
-    adb pull /etc/hostname
+    "${ADB}" pull /etc/hostname
     DEVICE=$(cat hostname)
     rm -f hostname
     if [ -z "${DEVICE}" ] ; then
@@ -51,14 +59,14 @@ detect_target_device()
 
 generate_initramfs()
 {
-    output=$(adb shell ls /usr/sbin/ostree-prepare-root)
+    output=$("${ADB}" shell ls /usr/sbin/ostree-prepare-root)
     substring="No such file or directory"
     if [[ $output == *${substring}* ]] ; then
         echo "error: Failed to find the required binary /usr/sbin/ostree-prepare-root on a device."
         exit 1
     fi
 
-    output=$(adb shell ls /lib/systemd/systemd)
+    output=$("${ADB}" shell ls /lib/systemd/systemd)
     systemd=false
     if [[ $output != *${substring}* ]] ; then
         systemd=true
@@ -74,20 +82,20 @@ generate_initramfs()
     if [ ${systemd} = true ] ; then
         # OSTree ships with a dracut module for systemd based images.
         echo "Generating initramfs for systemd based image ..."
-        adb push ${ROOT}/systemd/01-qt.conf /etc/dracut.conf.d/
+        "${ADB}" push ${ROOT}/systemd/01-qt.conf /etc/dracut.conf.d/
         custom_options='--add systemd'
     else
         # Deploy our custom dracut module for systemd-less images.
         echo "Generating initramfs for system v init based image ..."
         MODULE_PATH=/usr/lib/dracut/modules.d/98ostree/
-        adb shell mkdir -p $MODULE_PATH
-        adb push ${ROOT}/systemv/module-setup.sh $MODULE_PATH
-        adb push ${ROOT}/systemv/prepare-root.sh $MODULE_PATH
+        "${ADB}" shell mkdir -p $MODULE_PATH
+        "${ADB}" push ${ROOT}/systemv/module-setup.sh $MODULE_PATH
+        "${ADB}" push ${ROOT}/systemv/prepare-root.sh $MODULE_PATH
         custom_options='--omit systemd'
     fi
 
     # Terminate when the explicitly required modules could not be found or installed.
-    adb shell dracut ${options} ${custom_options} | tee dracut.log
+    "${ADB}" shell dracut ${options} ${custom_options} | tee dracut.log
     errors=$(cat dracut.log | grep -i "cannot be found or installed" | wc -l)
     if [ ${errors} -gt 0 ] ; then
         echo "error: Failed to include the required modules into the initramfs image."
@@ -95,9 +103,9 @@ generate_initramfs()
     fi
 
     rm -f initramfs.img
-    adb pull /boot/initramfs.img
-    device=$(adb shell uname -n | tr -d '\r')
-    release=$(adb shell uname -r | tr -d '\r' | cut -d'-' -f1)
+    "${ADB}" pull /boot/initramfs.img
+    device=$("${ADB}" shell uname -n | tr -d '\r')
+    release=$("${ADB}" shell uname -r | tr -d '\r' | cut -d'-' -f1)
     INITRAMFS=initramfs-${device}-${release}
     rm -rf ${INITRAMFS}
 
